/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleDBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int CREATE_TABLE = 9;
  /** RegularExpression Id. */
  int NOT_NULL = 10;
  /** RegularExpression Id. */
  int PRIMARY_KEY = 11;
  /** RegularExpression Id. */
  int FOREIGN_KEY = 12;
  /** RegularExpression Id. */
  int REFERENCES = 13;
  /** RegularExpression Id. */
  int DROP_TABLE = 14;
  /** RegularExpression Id. */
  int DESC = 15;
  /** RegularExpression Id. */
  int SHOW_TABLES = 16;
  /** RegularExpression Id. */
  int SELECT = 17;
  /** RegularExpression Id. */
  int ASTERISK = 18;
  /** RegularExpression Id. */
  int AS = 19;
  /** RegularExpression Id. */
  int FROM = 20;
  /** RegularExpression Id. */
  int WHERE = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int NOT = 24;
  /** RegularExpression Id. */
  int IS = 25;
  /** RegularExpression Id. */
  int INSERT_INTO = 26;
  /** RegularExpression Id. */
  int VALUES = 27;
  /** RegularExpression Id. */
  int NULL = 28;
  /** RegularExpression Id. */
  int DELETE_FROM = 29;
  /** RegularExpression Id. */
  int IS_NULL = 30;
  /** RegularExpression Id. */
  int IS_NOT_NULL = 31;
  /** RegularExpression Id. */
  int SEMICOLON = 32;
  /** RegularExpression Id. */
  int LEFT_PAREN = 33;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int UNDERSCORE = 36;
  /** RegularExpression Id. */
  int INT_VALUE = 37;
  /** RegularExpression Id. */
  int SIGN = 38;
  /** RegularExpression Id. */
  int DIGIT = 39;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 40;
  /** RegularExpression Id. */
  int ALPHABET = 41;
  /** RegularExpression Id. */
  int PERIOD = 42;
  /** RegularExpression Id. */
  int L = 43;
  /** RegularExpression Id. */
  int G = 44;
  /** RegularExpression Id. */
  int LE = 45;
  /** RegularExpression Id. */
  int GE = 46;
  /** RegularExpression Id. */
  int EQ = 47;
  /** RegularExpression Id. */
  int NEQ = 48;
  /** RegularExpression Id. */
  int QUOTE = 49;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARACTER = 50;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARACTER = 51;
  /** RegularExpression Id. */
  int CHAR_STRING = 52;
  /** RegularExpression Id. */
  int DATE_VALUE = 53;
  /** RegularExpression Id. */
  int NNNN = 54;
  /** RegularExpression Id. */
  int NN = 55;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"create table\"",
    "\"not null\"",
    "\"primary key\"",
    "\"foreign key\"",
    "\"references\"",
    "\"drop table\"",
    "\"desc\"",
    "\"show tables\"",
    "\"select\"",
    "\"*\"",
    "\"as\"",
    "\"from\"",
    "\"where\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"is\"",
    "\"insert into\"",
    "\"values\"",
    "\"null\"",
    "\"delete from\"",
    "\"is null\"",
    "\"is not null\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"_\"",
    "<INT_VALUE>",
    "<SIGN>",
    "<DIGIT>",
    "<LEGAL_IDENTIFIER>",
    "<ALPHABET>",
    "\".\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"!=\"",
    "\"\\\'\"",
    "<NON_QUOTE_SPECIAL_CHARACTER>",
    "<NON_QUOTE_CHARACTER>",
    "<CHAR_STRING>",
    "<DATE_VALUE>",
    "<NNNN>",
    "<NN>",
  };

}
