/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParserTokenManager.java */
//importimport java.io.*;
import java.util.*;
import com.sleepycat.je.Database;
import com.sleepycat.je.DatabaseException;
import com.sleepycat.je.DatabaseConfig;
import com.sleepycat.je.Cursor;
import com.sleepycat.je.DatabaseEntry;
import com.sleepycat.je.LockMode;
import com.sleepycat.je.OperationStatus;
import com.sleepycat.je.Environment;
import com.sleepycat.je.EnvironmentConfig;

/** Token Manager. */
public class SimpleDBMSParserTokenManager implements SimpleDBMSParserConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0xfffbffe0L) != 0L)
         {
            jjmatchedKind = 40;
            return 22;
         }
         if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 50;
            return -1;
         }
         if ((active0 & 0x2000000000000L) != 0L)
            return 23;
         return -1;
      case 1:
         if ((active0 & 0xc2480000L) != 0L)
            return 22;
         if ((active0 & 0x3db3ffe0L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 1;
            }
            return 22;
         }
         if ((active0 & 0x1000000000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 50;
               jjmatchedPos = 0;
            }
            return -1;
         }
         return -1;
      case 2:
         if ((active0 & 0x1800440L) != 0L)
            return 22;
         if ((active0 & 0x3c33fba0L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 2;
            }
            return 22;
         }
         return -1;
      case 3:
         if ((active0 & 0x2c237a00L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 3;
            return 22;
         }
         if ((active0 & 0x101081a0L) != 0L)
            return 22;
         return -1;
      case 4:
         if ((active0 & 0x200000L) != 0L)
            return 22;
         if ((active0 & 0x14000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x2c023a00L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 4;
            return 22;
         }
         return -1;
      case 5:
         if ((active0 & 0x8020000L) != 0L)
            return 22;
         if ((active0 & 0x14000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x24003a00L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 5;
            return 22;
         }
         return -1;
      case 6:
         if ((active0 & 0x14000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x3800L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 6;
            return 22;
         }
         if ((active0 & 0x24000200L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 7:
         if ((active0 & 0x14000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x2000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 7;
            return 22;
         }
         if ((active0 & 0x1800L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x24000200L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 8:
         if ((active0 & 0x14000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x2000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 8;
            return 22;
         }
         if ((active0 & 0x1800L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x24000200L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 9:
         if ((active0 & 0x14000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x2000L) != 0L)
            return 22;
         if ((active0 & 0x1800L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x24000200L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      case 10:
         if ((active0 & 0x10000L) != 0L)
         {
            if (jjmatchedPos < 3)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 3;
            }
            return -1;
         }
         if ((active0 & 0x1800L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x24000200L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 40;
               jjmatchedPos = 5;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 32:
         return jjStopAtPos(0, 1);
      case 33:
         return jjMoveStringLiteralDfa1_0(0x1000000000000L);
      case 39:
         return jjStartNfaWithStates_0(0, 49, 23);
      case 40:
         return jjStopAtPos(0, 33);
      case 41:
         return jjStopAtPos(0, 34);
      case 42:
         return jjStopAtPos(0, 18);
      case 44:
         return jjStopAtPos(0, 35);
      case 46:
         return jjStopAtPos(0, 42);
      case 59:
         return jjStopAtPos(0, 32);
      case 60:
         jjmatchedKind = 43;
         return jjMoveStringLiteralDfa1_0(0x200000000000L);
      case 61:
         return jjStopAtPos(0, 47);
      case 62:
         jjmatchedKind = 44;
         return jjMoveStringLiteralDfa1_0(0x400000000000L);
      case 95:
         return jjStopAtPos(0, 36);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x880000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x280L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x2000c100L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x20L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x101000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0xc6000040L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x11000400L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x2000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x30000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa1_0(0x200000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 61:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStopAtPos(1, 45);
         else if ((active0 & 0x400000000000L) != 0L)
            return jjStopAtPos(1, 46);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStopAtPos(1, 48);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000100L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x2002a000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x210080L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x4800040L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x1001400L);
      case 82:
      case 114:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(1, 22, 22);
         return jjMoveStringLiteralDfa2_0(active0, 0x104a00L);
      case 83:
      case 115:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(1, 19, 22);
         else if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0xc0000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x20L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa3_0(active0, 0xc0000000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x80L);
      case 68:
      case 100:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(2, 23, 22);
         break;
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x200200L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x820L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x38020000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x114000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x4008000L);
      case 84:
      case 116:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(2, 6, 22);
         else if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x500L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa4_0(active0, 0x400L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x200L);
      case 67:
      case 99:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(3, 15, 22);
         break;
      case 69:
      case 101:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 8, 22);
         return jjMoveStringLiteralDfa4_0(active0, 0x24023000L);
      case 76:
      case 108:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(3, 28, 22);
         break;
      case 77:
      case 109:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(3, 20, 22);
         return jjMoveStringLiteralDfa4_0(active0, 0x800L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0xc0000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      case 82:
      case 114:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(3, 7, 22);
         return jjMoveStringLiteralDfa4_0(active0, 0x200000L);
      case 84:
      case 116:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(3, 5, 22);
         break;
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa5_0(active0, 0x14000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x800L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000L);
      case 69:
      case 101:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(4, 21, 22);
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x400L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x4002000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000200L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa6_0(active0, 0x20002200L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x800L);
      case 83:
      case 115:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(5, 27, 22);
         break;
      case 84:
      case 116:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(5, 17, 22);
         return jjMoveStringLiteralDfa6_0(active0, 0x84014000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa7_0(active0, 0xa4000200L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x14000L);
      case 76:
      case 108:
         if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(6, 30);
         return jjMoveStringLiteralDfa7_0(active0, 0x400L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x3000L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa7_0(active0, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa8_0(active0, 0x1800L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa8_0(active0, 0x14000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000000L);
      case 76:
      case 108:
         if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(7, 10);
         break;
      case 78:
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x200L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x200L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0x2000L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa9_0(active0, 0x1800L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0x14000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0x4000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         return jjMoveStringLiteralDfa10_0(active0, 0x200L);
      case 69:
      case 101:
         if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(9, 14);
         return jjMoveStringLiteralDfa10_0(active0, 0x11800L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa10_0(active0, 0x80000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000000L);
      case 83:
      case 115:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(9, 13, 22);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 76:
      case 108:
         if ((active0 & 0x80000000L) != 0L)
            return jjStopAtPos(10, 31);
         return jjMoveStringLiteralDfa11_0(active0, 0x200L);
      case 77:
      case 109:
         if ((active0 & 0x20000000L) != 0L)
            return jjStopAtPos(10, 29);
         break;
      case 79:
      case 111:
         if ((active0 & 0x4000000L) != 0L)
            return jjStopAtPos(10, 26);
         break;
      case 83:
      case 115:
         if ((active0 & 0x10000L) != 0L)
            return jjStopAtPos(10, 16);
         break;
      case 89:
      case 121:
         if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(10, 11);
         else if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(10, 12);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(11, 9);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 23;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0xffffff7b00000000L & l) != 0L)
                  {
                     if (kind > 51)
                        kind = 51;
                  }
                  else if (curChar == 39)
                     jjCheckNAddTwoStates(3, 4);
                  if ((0xfc00ff7a00000000L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 37)
                        kind = 37;
                     jjCheckNAddStates(0, 3);
                  }
                  if ((0x280000000000L & l) != 0L)
                  {
                     if (kind > 38)
                        kind = 38;
                     jjCheckNAdd(6);
                  }
                  break;
               case 23:
                  if ((0xffffff7b00000000L & l) != 0L)
                     jjCheckNAddTwoStates(3, 4);
                  else if (curChar == 39)
                  {
                     if (kind > 52)
                        kind = 52;
                  }
                  break;
               case 1:
                  if ((0xffffff7b00000000L & l) != 0L && kind > 51)
                     kind = 51;
                  break;
               case 2:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 3:
                  if ((0xffffff7b00000000L & l) != 0L)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 4:
                  if (curChar == 39 && kind > 52)
                     kind = 52;
                  break;
               case 5:
                  if ((0x280000000000L & l) == 0L)
                     break;
                  if (kind > 38)
                     kind = 38;
                  jjCheckNAdd(6);
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 37)
                     kind = 37;
                  jjCheckNAdd(6);
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 37)
                     kind = 37;
                  jjCheckNAddStates(0, 3);
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 11:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 12:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 14:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 16:
                  if ((0x3ff000000000000L & l) != 0L && kind > 53)
                     kind = 53;
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) != 0L && kind > 54)
                     kind = 54;
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) != 0L && kind > 55)
                     kind = 55;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffffffffffffL & l) != 0L)
                  {
                     if (kind > 51)
                        kind = 51;
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 40)
                        kind = 40;
                     jjCheckNAdd(22);
                  }
                  else if ((0x78000001f8000001L & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                  }
                  break;
               case 23:
               case 3:
                  if ((0x7fffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(3, 4);
                  break;
               case 1:
                  if ((0x7fffffffffffffffL & l) != 0L && kind > 51)
                     kind = 51;
                  break;
               case 21:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAdd(22);
                  break;
               case 22:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAdd(22);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 23 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   6, 8, 17, 20, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, "\52", null, null, null, null, null, null, null, null, 
null, null, null, null, null, "\73", "\50", "\51", "\54", "\137", null, null, null, 
null, null, "\56", "\74", "\76", "\74\75", "\76\75", "\75", "\41\75", "\47", null, 
null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffffffffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[23];
static private final int[] jjstateSet = new int[46];
static protected char curChar;
/** Constructor. */
public SimpleDBMSParserTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public SimpleDBMSParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 23; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 13 && (0x2600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
